import { createEmailDataAttachmentsFromFiles } from '../../attachment/build-in/create-email-data-attachments-from-files';
import { IEmailDataAttachment } from '../../attachment/email-data-attachment.type';
import { IEmailDataMultipart } from '../email-data-multipart.type';
import {
  createEmailDataMultipartWithAutogeneratedBoundary,
  ICreateEmailDataMultipartWithAutogeneratedBoundaryOptions,
} from './create-email-data-multipart-with-autogenerated-boundary';

export interface ICreateEmailDataMultipartMixedFromFilesOptions extends Omit<ICreateEmailDataMultipartWithAutogeneratedBoundaryOptions, 'content' | 'mimeTypeSubtype'> {
  files: readonly File[];
}

export function createEmailDataMultipartMixedFromFiles(
  {
    files,
    ...options
  }: ICreateEmailDataMultipartMixedFromFilesOptions,
): Promise<IEmailDataMultipart> {
  return createEmailDataAttachmentsFromFiles({
    files,
  })
    .then((attachments: IEmailDataAttachment[]): IEmailDataMultipart => {
      return createEmailDataMultipartWithAutogeneratedBoundary({
        ...options,
        content: attachments,
        mimeTypeSubtype: 'mixed',
      });
    });
}
