import { createEmailDataTextHTML } from '../../text/html/create-email-data-text-html';
import { createEmailDataTextPlain } from '../../text/plain/create-email-data-text-plain';
import { IEmailDataMultipart } from '../email-data-multipart.type';
import {
  createEmailDataMultipartWithAutogeneratedBoundary,
  ICreateEmailDataMultipartWithAutogeneratedBoundaryOptions,
} from './create-email-data-multipart-with-autogenerated-boundary';

export interface ICreateEmailDataMultipartAlternativeFromTextAndHTMLOptions extends Omit<ICreateEmailDataMultipartWithAutogeneratedBoundaryOptions, 'content' | 'mimeTypeSubtype'> {
  text: string;
  html: string;
}

export function createEmailDataMultipartAlternativeFromTextAndHTML(
  {
    text,
    html,
    ...options
  }: ICreateEmailDataMultipartAlternativeFromTextAndHTMLOptions,
): IEmailDataMultipart {
  return createEmailDataMultipartWithAutogeneratedBoundary({
    ...options,
    content: [
      createEmailDataTextPlain({
        text,
      }),
      createEmailDataTextHTML({
        html,
      }),
    ],
    mimeTypeSubtype: 'alternative',
  });
}
